services:
  backend:
    build: ./backend
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - mongo_network
  frontend:
    build: ./frontend
    ports:
      - '8080:8080'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - mongo_network
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    networks:
      - mongo_network
      
networks:
  mongo_network:
    name: mongo_network
    driver: bridge